#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: application-istio
#  annotations:
#    kubernetes.io/ingress.class: istio
#spec:
#  # ingressClassName: nginx
#  rules:
#    - host: "foo.localhost"
#      http:
#        paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: application
#                port:
#                  number: 80
#  tls:
#    - hosts:
#        - "foo.localhost"
#      secretName: application-tls