apiVersion: v1
kind: Service
metadata:
  name: foo-app
  namespace: istio-gateway-system
spec:
  selector:
    app: foo-app
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bar-app
  namespace: istio-gateway-system
spec:
  selector:
    app: bar-app
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80