apiVersion: v1
kind: Service
metadata:
  name: application
spec:
  selector:
    app: application
  type: ClusterIP
  ports:
    - protocol: TCP
      name: grpc-plain
      port: 9000
      targetPort: 9000
    - protocol: TCP
      name: grpc-tls
      port: 9443
      targetPort: 9443